name: to_do_list_android
description: "CS 442 final project"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.0.0
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.0
  path_provider: ^2.1.1
  http: ^1.1.0
  collection: ^1.17.2
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true

   # to add assets to the app, do something like this:
  # assets: 
  #   - assets/